### ISSUE TITLE
裏面いじってみた

### ISSUE THREAD

**Issue by ryu-g** [sKawashima/mb-leaflet#3]
![2018-06-22 15 50 09](https://user-images.githubusercontent.com/9881744/41762044-5f50a4da-7634-11e8-8046-715ddab2180e.png)
- 営業時間追加
- 連絡先(電話)追加
- 連絡先(mail)追加
- 地図のオブジェクト少しいじった
- オブジェクト間すし詰め状態だったのですこしゆとりもたせた
- sns文字の大きさ揃えた

**Comment by sKawashima** [comment]
ありがてえ…ありがてえ…

**Comment by sKawashima** [comment]
<img width="325" alt="2018-06-23 21 01 45" src="https://user-images.githubusercontent.com/9900753/41809460-df2d2bac-7728-11e8-91ae-8e77bbd35289.png">
ミス発見しちゃった
